TEMPLATE_DIR = $(HOME)/Library/Developer/Xcode/Templates/FuturedArchitecture

install:
	mkdir -p $(TEMPLATE_DIR)
	cp -R *.xctemplate $(TEMPLATE_DIR)/
	echo "\033[0;32mInstallation was successful!\033[0m"

.PHONY: install
.SILENT: install
